### ISSUE TITLE
[Frontend] Initial Structure for GoJS Implementation

### ISSUE THREAD

**Issue by burakmert236** [burakmert236/CMPE492-Modeling-Editor#1]
***Description*:**
Implementing initial structure of Canvas and Toolbar using GoJS.

***Todo's*:**
- [x] Importing necessary libraries.
- [x] Implementing initial structure for canvas and toolbar.
- [x] Making necessary state connections to use GoJS Diagram object in other React components.

***Related Branches*:** [frontend-initial-gojs](https://github.com/burakmert236/CMPE492-Modeling-Editor/tree/frontend-initial-gojs), [frontend-initial-gojs-improvements](https://github.com/burakmert236/CMPE492-Modeling-Editor/tree/frontend-initial-gojs-improvements)

***Reviewer*:** @

***Task Deadline*:** 29.03.2023 17:00

**Comment by burakmert236** [comment]
Since the related pull request is accepted, I am closing the issue.
